export const GET_INFORMATIONS = 'GET_INFORMATIONS';
export const INFORMATION_ERROR = 'INFORMATION_ERROR'
export const GET_ARTICLE = 'GET_ARTICLE'
export const ARTICLE_ERROR = 'ARTICLE_ERROR'
export const GET_PROJECT = 'GET_PROJECT'
export const PROJECT_ERROR = 'PROJECT_ERROR'

export const UPDATE_LIKE = "UPDATE_LIKE"
